### ISSUE TITLE
Query: Largest Job Seekers

### ISSUE THREAD

**Issue by Grantskie** [1086-Maria-Big-Data/JobAdAnalytics#17]
What are the three companies posting the most tech job ads?

**Comment by Ahimsaka** [comment]
We're continuing to explore other implementations in case we can find a more accurate count, but our bare-minimum emergency fallback option is this: 

`    val spark = AppSparkSession()

    import spark.implicits._

    val df = spark.sqlContext.read
      .option("header", true)
      .schema(IndexUtil.schema)
      .csv("s3a://maria-1086/FilteredIndex/CC-MAIN-2021-**/*.csv")

    df.groupBy("url_host_name")
      .count()
      .orderBy(desc("count"))
      .show(20, false)
`

This works. 

Result is this: 

+--------------------------+-----+
|url_host_name             |count|
+--------------------------+-----+
|www.military.com          |94856|
|www.adeccousa.com         |91094|
|www.ihirechefs.com        |38222|
|veteranjobs.edwards.com   |35520|
|careers.bankofamerica.com |30637|
|careers.gijobs.com        |26187|
|jobsus.deloitte.com       |26019|
|militaryjobs.homedepot.com|25630|
|careers.cognizant.com     |22773|
|www.themuse.com           |21831|
|www.monsterindia.com      |21629|
|www.timesjobs.com         |21480|
|www.randstadusa.com       |20450|
|datafloq.com              |19383|
|www.freshersworld.com     |17362|
|m.timesjobs.com           |17058|
|www.dice.com              |15633|
|www.techfetch.com         |15328|
|venturefizz.com           |15164|
|www.shine.com             |15115|
+--------------------------+-----+

I need to do a little human parsing to determine which of these would be valid answers but if we had to submit this as our final result I wouldn't be upset.

**Comment by Ahimsaka** [comment]
Military.com
Edwards.com
Bankofamerica.com
Deloitte.com
Cognizant.com

These are all valid answers. The rest are job boards. They're also all plausible answers.

**Comment by JesseJSabbath** [comment]
Added minimal fallback query on branch [jLargestJob](https://github.com/1086-Maria-Big-Data/JobAdAnalytics/tree/jLargestJob) . Current largestJob class in main contains what appears to be some preliminary efforts to write a filtered index. If that needs to be retained for any reason, please migrate it elsewhere and then create a pull request.
