### ISSUE TITLE
Query: Tech Job Posting Trends

### ISSUE THREAD

**Issue by Grantskie** [1086-Maria-Big-Data/JobAdAnalytics#18]
Is there a general trend in tech job postings over the past year?
What about the past month?

**Comment by kylejwolff** [comment]
I'm trying to create a DataFrame that looks like this:
![image](https://user-images.githubusercontent.com/5702229/132032746-c692105b-fb4a-4274-9526-1a3bd3467e08.png)
Then I'll query it with groupBy(date).sum

**Comment by kylejwolff** [comment]
Trying to create a csv on my own EMR cluster for CC-MAIN-2021-31 which includes July/August.  I can just put that on the group's S3 bucket if/when I succeed

**Comment by brja3022** [comment]
Creating csvs based on the index getting trends for keywords that appear in the url. Using all the 2020 and 2021 crawls. This will be used if Kyle's method does not succeed in time
![DataJobs](https://user-images.githubusercontent.com/49416679/132052644-7d01cf69-346d-4744-8aab-df64e4dbc22d.PNG)

**Comment by kylejwolff** [comment]
That should work for an MVP.  I'm going to spend the weekend trying to get a wordCount from the playloads.  If I can't get something going by Sunday we'll just use the index since everyone else is using it anyway.

**Comment by kylejwolff** [comment]
Closed by #88
