### ISSUE TITLE
Determine file structure and file formatting of common crawl data

### ISSUE THREAD

**Issue by Grantskie** [1086-Maria-Big-Data/JobAdAnalytics#24]

**Comment by brja3022** [comment]
![CommonCrawlHierarchy](https://user-images.githubusercontent.com/49416679/131540609-95e7bd02-81de-4c07-a154-53558beafbda.png)
We found that the common crawl dataset is divided into crawls for the different time frame. Each crawl contains the website data for 1 or 2 months. Each crawl contains multiple segments with each segment containing warc files. A warc file contains metadata and the html code for a website.
