### ISSUE TITLE
Access common crawl data through its S3 bucket

### ISSUE THREAD

**Issue by Grantskie** [1086-Maria-Big-Data/JobAdAnalytics#25]

**Comment by vinceecws** [comment]
#4 Sucessfully implements utility for loading CommonCrawl Dataset Index as specified: 
https://github.com/commoncrawl/cc-index-table/blob/a47d8eb9110ffd833b67889d02e5ee419806e11f/src/sql/athena/cc-index-create-table-flat.sql#L8-L42

**Comment by vinceecws** [comment]
#36 Implements querying WARC records from the CommonCrawl Dataset by creating CDX records from query results returned by the Index.

A toy example of how to do so would be:
