### ISSUE TITLE
Query and filter common crawl index table

### ISSUE THREAD

**Issue by Grantskie** [1086-Maria-Big-Data/JobAdAnalytics#26]

**Comment by brja3022** [comment]
Filtered index table to get individual crawls, files in the subset warc, and urls that contain keywords related to jobs. This filtering is done in TestExtract in the file CCIndexMain.scala.

**Comment by brja3022** [comment]
https://github.com/1086-Maria-Big-Data/JobAdAnalytics/blob/950394711879f09195bc6dfb0e06d2fcc32f9f60/src/main/scala/cc/idx/CCIdxMain.scala#L78-L80
#12
