### ISSUE TITLE
Access WARC objects within the WARC files

### ISSUE THREAD

**Issue by Grantskie** [1086-Maria-Big-Data/JobAdAnalytics#28]

**Comment by vinceecws** [comment]
Implemented by #13 

https://github.com/1086-Maria-Big-Data/JobAdAnalytics/blob/5a9cd745bcb7ff2d27aed1473e02f8faac6683e6/src/main/scala/cc/warc/warcUtil.scala#L73-L169

This pull request implements the `SuperWarc` class, which is a wrapper class to enable much easier access to the `WarcRecord` objects from ArchiveSpark, including it's metadata type fields `mime`, `status`, `originalUrl` etc.

**Comment by vinceecws** [comment]
Usage example:

https://github.com/1086-Maria-Big-Data/JobAdAnalytics/blob/bb1fb654db175f056e1f2a4ceadeda2dc56a32ee/src/main/scala/cc/warc/CCWarcMain.scala#L17-L35

1) The above snippet loads the `.warc.gz` file from the CommonCrawl S3 bucket
2) `WarcUtil.load()` takes care of parsing the `WARC` files into `RDD[WarcRecord]`
3) Right after `.take(3)`, the  `.map(x => SuperWarc(x))` is called on `RDD[WarcRecord]` to wrap `WarcRecord` objects into `SuperWarc`
4) Now, all the fields available are accessible as instance attributes on the `SuperWarc` instances.
