### ISSUE TITLE
Access webpage HTML from within the WARC objects

### ISSUE THREAD

**Issue by Grantskie** [1086-Maria-Big-Data/JobAdAnalytics#29]

**Comment by brja3022** [comment]
#13 Using the SuperWarc class extracted the payload of the WARC record. This contains the HTML of the original webpage. Also provided an option textOnly in the payload that can get just the text from the HTML. Code found in warcUtil.scala.

**Comment by vinceecws** [comment]
`SuperWarc class`:
https://github.com/1086-Maria-Big-Data/JobAdAnalytics/blob/950394711879f09195bc6dfb0e06d2fcc32f9f60/src/main/scala/cc/warc/warcUtil.scala#L73
