### ISSUE TITLE
Parse HTML into a usable format

### ISSUE THREAD

**Issue by Grantskie** [1086-Maria-Big-Data/JobAdAnalytics#30]

**Comment by vinceecws** [comment]
Refer to #28 

Additionally, in the `SuperWarc` class, there's an overloaded instance method:

https://github.com/1086-Maria-Big-Data/JobAdAnalytics/blob/5a9cd745bcb7ff2d27aed1473e02f8faac6683e6/src/main/scala/cc/warc/warcUtil.scala#L167-L168

The above methods retrieve the corresponding WARC payload, where if the overloaded method with `textOnly=true` is invoked, it returns the text-only HTML payload, where all the HTML tags are removed.
