### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by williamgantterry** [1086-Maria-Big-Data/JobAdAnalytics#71]
http://www.russellspitzer.com/2017/02/27/Concurrency-In-Spark/ for concurrency in spark and it has a "
 A singleton object that controls the parallelism on a Single Executor JVM", also some code for Cassandra which Im not suggesting we add at this point

looks like repartitioning may be best and quickest fix as done in IndexUtil.write

I am trying this on EMR with entryLevel

**Comment by vinceecws** [comment]
A good place to start: http://www.russellspitzer.com/2017/02/27/Concurrency-In-Spark/

**Comment by rustle003** [comment]
Insufficient time to explore as of this moment.
