### ISSUE TITLE
Output for FilteredIndex should not delimit by ","

### ISSUE THREAD

**Issue by vinceecws** [1086-Maria-Big-Data/JobAdAnalytics#79]
The SURT URL column contains "," in its values:
<img width="741" alt="Screen Shot 2021-09-02 at 8 33 17 PM" src="https://user-images.githubusercontent.com/19466657/131932846-7f958f6a-0964-4c49-b123-2c59e67661bc.png">

So, a comma delimited output format for FilteredIndex will not be ideal. A better choice would be to delimit by whitespace.

**Comment by Ahimsaka** [comment]
I believe we resolved this yesterday when Vince added a delimiter parameter to IndexUtil.write

**Comment by vinceecws** [comment]
This issue was opened due to an ignorance of how Spark internally handles conflicts in field values with delimiters by wrapping the entire field with quotation marks.

Using the above example, if the delimiter specified in Spark is "," and the field contains "," like `com,hellosummerville)/jobs/law-enforcement-security`, Spark DataFrameWriter will automatically handle that by wrapping the field with quotation marks like so `"com,hellosummerville)/jobs/law-enforcement-security"`.
